apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - rbac.yaml
  - service.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: k8s-leader-example
    literals:
      - LEASE_DURATION=30
      - RENEWAL_DEADLINE=15
      - RETRY_PERIOD=10
