apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-leader-example
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - "*"
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding:app1-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-leader-example
subjects:
  - kind: ServiceAccount
    name: k8s-leader-example
