apiVersion: v1
kind: Service
metadata:
  name: k8s-leader-example
spec:
  selector:
    app: k8s-leader-example
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
