apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: getting-started-kustomize
build:
  artifacts:
    - image: ghcr.io/iterative/studio-selfhosted
      context: .
      runtimeType: go
      docker:
        
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - kustomize
deploy:
  kubectl: {}
